"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 20:43:43.541078
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    op.create_table('audit_events',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='user | system | worker | scheduler'),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_execution_id'), 'audit_events', ['execution_id'], unique=False)
    op.create_index('ix_audit_ws_created', 'audit_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('llm_providers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.Enum('openai', 'anthropic', 'ollama', 'fake', name='provider_type', native_enum=False, length=40), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_secret_ref', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_llm_providers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_providers')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_llm_providers_workspace_id_name'))
    )
    op.create_index(op.f('ix_llm_providers_workspace_id'), 'llm_providers', ['workspace_id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.Enum('stdio', 'streamable_http', 'sse_legacy', name='transport', native_enum=False, length=40), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cwd', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('env_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('header_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('isolation', sa.Enum('shared', 'per_execution', name='isolation', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('disconnected', 'connecting', 'initializing', 'discovering', 'ready', 'reconnecting', 'failed', name='server_status', native_enum=False, length=40), nullable=False),
    sa.Column('status_message', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connect_timeout_s', sa.Double(), nullable=False),
    sa.Column('call_timeout_s', sa.Double(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('command_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(transport = 'stdio' AND command IS NOT NULL) OR (transport <> 'stdio' AND url IS NOT NULL)", name=op.f('ck_mcp_servers_transport_target')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mcp_servers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers')),
    sa.UniqueConstraint('workspace_id', 'slug', name=op.f('uq_mcp_servers_workspace_id_slug'))
    )
    op.create_index(op.f('ix_mcp_servers_workspace_id'), 'mcp_servers', ['workspace_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel_type', sa.Enum('webhook', 'slack', 'discord', name='channel_type', native_enum=False, length=40), nullable=False),
    sa.Column('url_secret_ref', sa.String(length=80), nullable=False),
    sa.Column('signing_secret_ref', sa.String(length=80), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_delivery_ok', sa.Boolean(), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_notification_channels_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_notification_channels_workspace_id_name'))
    )
    op.create_index(op.f('ix_notification_channels_workspace_id'), 'notification_channels', ['workspace_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latest_version_id', sa.UUID(), nullable=True),
    sa.Column('latest_version_number', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('webhook_secret_ref', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['latest_version_id'], ['pipeline_versions.id'], name=op.f('fk_pipelines_latest_version_id_pipeline_versions'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pipelines_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines')),
    sa.UniqueConstraint('workspace_id', 'slug', name=op.f('uq_pipelines_workspace_id_slug'))
    )
    op.create_index(op.f('ix_pipelines_workspace_id'), 'pipelines', ['workspace_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_prompt_templates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_prompt_templates_workspace_id_name'))
    )
    op.create_index(op.f('ix_prompt_templates_workspace_id'), 'prompt_templates', ['workspace_id'], unique=False)
    op.create_table('prompt_variables',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_prompt_variables_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_variables')),
    sa.UniqueConstraint('workspace_id', 'key', name=op.f('uq_prompt_variables_workspace_id_key'))
    )
    op.create_index(op.f('ix_prompt_variables_workspace_id'), 'prompt_variables', ['workspace_id'], unique=False)
    op.create_table('secrets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_data_key', sa.LargeBinary(), nullable=False),
    sa.Column('key_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('hint', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('managed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='created implicitly for a config field'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_secrets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_secrets_workspace_id_name'))
    )
    op.create_index(op.f('ix_secrets_workspace_id'), 'secrets', ['workspace_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_user_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'operator', 'viewer', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_members_workspace_id_user_id'))
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('llm_models',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_json_schema', sa.Boolean(), nullable=False),
    sa.Column('default_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('input_price_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_price_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], name=op.f('fk_llm_models_provider_id_llm_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_llm_models_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_models')),
    sa.UniqueConstraint('provider_id', 'model_name', name=op.f('uq_llm_models_provider_id_model_name'))
    )
    op.create_index(op.f('ix_llm_models_provider_id'), 'llm_models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_llm_models_workspace_id'), 'llm_models', ['workspace_id'], unique=False)
    op.create_table('mcp_tools',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('is_destructive', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level', native_enum=False, length=40), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], name=op.f('fk_mcp_tools_server_id_mcp_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mcp_tools_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_tools')),
    sa.UniqueConstraint('server_id', 'name', name=op.f('uq_mcp_tools_server_id_name'))
    )
    op.create_index(op.f('ix_mcp_tools_server_id'), 'mcp_tools', ['server_id'], unique=False)
    op.create_index(op.f('ix_mcp_tools_workspace_id'), 'mcp_tools', ['workspace_id'], unique=False)
    op.create_table('pipeline_versions',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_hash', sa.String(length=64), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pipeline_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_versions_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_versions')),
    sa.UniqueConstraint('pipeline_id', 'version', name=op.f('uq_pipeline_versions_pipeline_id_version'))
    )
    op.create_index(op.f('ix_pipeline_versions_pipeline_id'), 'pipeline_versions', ['pipeline_id'], unique=False)
    op.create_table('prompt_template_versions',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_prompt_template_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], name=op.f('fk_prompt_template_versions_template_id_prompt_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_template_versions')),
    sa.UniqueConstraint('template_id', 'version', name=op.f('uq_prompt_template_versions_template_id_version'))
    )
    op.create_index(op.f('ix_prompt_template_versions_template_id'), 'prompt_template_versions', ['template_id'], unique=False)
    op.create_table('schedules',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('interval', 'daily', 'cron', name='schedule_kind', native_enum=False, length=40), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('daily_time', sa.String(length=5), nullable=True, comment='HH:MM'),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('overlap_policy', sa.Enum('skip', 'queue', name='overlap_policy', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_schedules_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_schedules_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_pipeline_id'), 'schedules', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_schedules_workspace_id'), 'schedules', ['workspace_id'], unique=False)
    op.create_table('executions',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'schedule', 'webhook', 'restart', name='trigger_kind', native_enum=False, length=40), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('restarted_from_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'waiting_for_tool', 'waiting_for_timer', 'paused_for_review', 'paused', 'resuming', 'completed', 'failed', 'cancelled', name='execution_status', native_enum=False, length=40), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('retries_used', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_seq', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_executions_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_version_id'], ['pipeline_versions.id'], name=op.f('fk_executions_pipeline_version_id_pipeline_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restarted_from_id'], ['executions.id'], name=op.f('fk_executions_restarted_from_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_executions_schedule_id_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_executions_triggered_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_executions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_executions_thread_id'))
    )
    op.create_index('ix_executions_lease', 'executions', ['status', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_executions_pipeline_id'), 'executions', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_executions_pipeline_version_id'), 'executions', ['pipeline_version_id'], unique=False)
    op.create_index(op.f('ix_executions_workspace_id'), 'executions', ['workspace_id'], unique=False)
    op.create_index('ix_executions_ws_status_created', 'executions', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('durable_timers',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('wake_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_durable_timers_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_durable_timers')),
    sa.UniqueConstraint('execution_id', 'node_id', name=op.f('uq_durable_timers_execution_id_node_id'))
    )
    op.create_index(op.f('ix_durable_timers_wake_at'), 'durable_timers', ['wake_at'], unique=False)
    op.create_table('execution_events',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('execution.created', 'execution.started', 'execution.paused', 'execution.resumed', 'execution.completed', 'execution.failed', 'execution.cancelled', 'node.started', 'node.completed', 'node.failed', 'node.retrying', 'llm.requested', 'llm.completed', 'tool.requested', 'tool.awaiting_approval', 'tool.approved', 'tool.rejected', 'tool.executing', 'tool.completed', 'tool.failed', 'approval.created', 'approval.decided', 'mcp.server_status_changed', name='event_type', native_enum=False, length=40), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=True),
    sa.Column('tool_call_id', sa.UUID(), nullable=True),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_events_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_execution_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events')),
    sa.UniqueConstraint('execution_id', 'seq', name=op.f('uq_execution_events_execution_id_seq'))
    )
    op.create_index(op.f('ix_execution_events_workspace_id'), 'execution_events', ['workspace_id'], unique=False)
    op.create_table('execution_nodes',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.Enum('trigger', 'llm', 'agent', 'mcp_tool', 'condition', 'transform', 'human_approval', 'notification', 'delay', 'end', name='node_type', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', 'waiting', 'retrying', 'cancelled', name='node_status', native_enum=False, length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_nodes_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_nodes')),
    sa.UniqueConstraint('execution_id', 'node_id', name=op.f('uq_execution_nodes_execution_id_node_id'))
    )
    op.create_index(op.f('ix_execution_nodes_execution_id'), 'execution_nodes', ['execution_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True, comment='short output summary, never chain-of-thought'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_llm_usage_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], name=op.f('fk_llm_usage_provider_id_llm_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_llm_usage_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index(op.f('ix_llm_usage_execution_id'), 'llm_usage', ['execution_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_workspace_id'), 'llm_usage', ['workspace_id'], unique=False)
    op.create_index('ix_llm_usage_ws_created', 'llm_usage', ['workspace_id', 'created_at'], unique=False)
    op.create_table('schedule_fires',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False, comment='enqueued | skipped_overlap | failed'),
    sa.Column('fired_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_schedule_fires_execution_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_fires_schedule_id_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_fires')),
    sa.UniqueConstraint('schedule_id', 'fire_at', name=op.f('uq_schedule_fires_schedule_id_fire_at'))
    )
    op.create_index(op.f('ix_schedule_fires_schedule_id'), 'schedule_fires', ['schedule_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('call_seq', sa.Integer(), nullable=False),
    sa.Column('llm_tool_call_id', sa.String(length=120), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('tool_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('namespaced_name', sa.String(length=300), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'awaiting_approval', 'approved', 'executing', 'completed', 'failed', 'rejected', 'cancelled', 'timeout', 'outcome_unknown', name='tool_call_status', native_enum=False, length=40), nullable=False),
    sa.Column('policy_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_tool_calls_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], name=op.f('fk_tool_calls_server_id_mcp_servers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['mcp_tools.id'], name=op.f('fk_tool_calls_tool_id_mcp_tools'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tool_calls_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_tool_calls_idempotency_key'))
    )
    op.create_index('ix_tool_calls_exec_status', 'tool_calls', ['execution_id', 'status'], unique=False)
    op.create_index(op.f('ix_tool_calls_execution_id'), 'tool_calls', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_workspace_id'), 'tool_calls', ['workspace_id'], unique=False)
    op.create_table('approvals',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('tool_call', 'data_review', 'outcome_unknown', name='approval_kind', native_enum=False, length=40), nullable=False),
    sa.Column('tool_call_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'superseded', 'expired', name='approval_status', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('original_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='data under review / context'),
    sa.Column('decision', sa.String(length=40), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed', sa.Boolean(), nullable=False, comment='decision consumed by the worker'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_approvals_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['approvals.id'], name=op.f('fk_approvals_superseded_by_approvals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], name=op.f('fk_approvals_tool_call_id_tool_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_approvals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_execution_id'), 'approvals', ['execution_id'], unique=False)
    op.create_index(op.f('ix_approvals_expires_at'), 'approvals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approvals_workspace_id'), 'approvals', ['workspace_id'], unique=False)
    op.create_index('ix_approvals_ws_status', 'approvals', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_index('uq_approvals_pending_tool_call', 'approvals', ['tool_call_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))

    # audit_events is append-only at the database level.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only (% rejected)', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER audit_events_no_update_delete BEFORE UPDATE OR DELETE ON audit_events "
        "FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()"
    )
    op.execute(
        "CREATE TRIGGER audit_events_no_truncate BEFORE TRUNCATE ON audit_events "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only()"
    )
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON audit_events FROM PUBLIC")
    op.execute(
        """
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'agent_platform_app') THEN
                REVOKE UPDATE, DELETE, TRUNCATE ON audit_events FROM agent_platform_app;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_update_delete ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_approvals_pending_tool_call', table_name='approvals', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_approvals_ws_status', table_name='approvals')
    op.drop_index(op.f('ix_approvals_workspace_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_expires_at'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_execution_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_tool_calls_workspace_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_execution_id'), table_name='tool_calls')
    op.drop_index('ix_tool_calls_exec_status', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_schedule_fires_schedule_id'), table_name='schedule_fires')
    op.drop_table('schedule_fires')
    op.drop_index('ix_llm_usage_ws_created', table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_workspace_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_execution_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_execution_nodes_execution_id'), table_name='execution_nodes')
    op.drop_table('execution_nodes')
    op.drop_index(op.f('ix_execution_events_workspace_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_durable_timers_wake_at'), table_name='durable_timers')
    op.drop_table('durable_timers')
    op.drop_index('ix_executions_ws_status_created', table_name='executions')
    op.drop_index(op.f('ix_executions_workspace_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_pipeline_version_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_pipeline_id'), table_name='executions')
    op.drop_index('ix_executions_lease', table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_schedules_workspace_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_pipeline_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_prompt_template_versions_template_id'), table_name='prompt_template_versions')
    op.drop_table('prompt_template_versions')
    op.drop_index(op.f('ix_pipeline_versions_pipeline_id'), table_name='pipeline_versions')
    op.drop_table('pipeline_versions')
    op.drop_index(op.f('ix_mcp_tools_workspace_id'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_server_id'), table_name='mcp_tools')
    op.drop_table('mcp_tools')
    op.drop_index(op.f('ix_llm_models_workspace_id'), table_name='llm_models')
    op.drop_index(op.f('ix_llm_models_provider_id'), table_name='llm_models')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_secrets_workspace_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_prompt_variables_workspace_id'), table_name='prompt_variables')
    op.drop_table('prompt_variables')
    op.drop_index(op.f('ix_prompt_templates_workspace_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_pipelines_workspace_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_notification_channels_workspace_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_mcp_servers_workspace_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_llm_providers_workspace_id'), table_name='llm_providers')
    op.drop_table('llm_providers')
    op.drop_index('ix_audit_ws_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_execution_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
